### ISSUE TITLE
Crash when trying to receive image

### ISSUE THREAD

**Issue by RubberDuckShobe** [you-win/spout-gd#10]
Hello, I am trying to get video from OBS into Godot, but whenever I try to receive an image, it hangs for a bit and then crashes - with no error message.

I'm using this script to test:
```gdscript
var spout: Spout
var img: Image

func _ready():
	spout = Spout.new()
	
	spout.set_receiver_name("testing")
	spout.receive_image(img, Spout.FORMAT_BGRA)
```

I've verified the OBS Spout plugin works correctly using [the example Spout receiver](https://github.com/leadedge/Spout2/releases), which successfully gets the video from OBS. What could be going wrong here?

**Comment by erodozer** [comment]
Hi, you're missing a few steps.

Spout requires that you call `is_updated()` before you receive a frame.  You also need to initialize your image and make sure it's the correct dimensions based on the sender width and height before spout can write into it.

You can look at [this PR](https://github.com/you-win/spout-gd/pull/8) as an example of how to do it in GDScript (not very performant), or my fork which has a helper resource.

**Comment by RubberDuckShobe** [comment]
I see! I actually ended up using your fork because it does what I want even without a script, thank you!
