### ISSUE TITLE
Error loading extension: res://addons/spout_gd.gdextension

### ISSUE THREAD

**Issue by liz-forena** [you-win/spout-gd#13]
May be doing something wrong but every time I load the project after running the build.sh file it pops up with this error.

I'm pretty new to Godot, so some help would be awesome!

**Comment by you-win** [comment]
Did the `build.sh` script finish successfully?

Did you follow the instructions: "Move the .gdextension file + the dll in out/ + Spout2/Binaries/x64/SpoutLibrary.dll to a new folder in addons called spout-gd"

Your Godot folder structure should look something like (assuming a new project):
- icon.svg
- project.godot
- addons/
  - spout-gd/
    - spout_gd.windows.template_debug.dll

**Comment by liz-forena** [comment]
Thank you! I must have misread that part but its working now!
