### ISSUE TITLE
Unable to call send_image / send_texture 

### ISSUE THREAD

**Issue by MorseAmalgam** [you-win/spout-gd#5]
Using Godot v4.1.1.stable.official [bd6af8e0e]
After getting the library compiled, I could get it to load in my project. Following the example, I'm using:

```
var spout: Spout
@export var img: Texture2D

func _ready():
	spout = Spout.new()
	#img = $ASCII/FrameViewport/SubViewport.get_texture().get_image()
	spout.send_image(img.get_image(), img.get_width(), img.get_height())
```

 but upon trying to run it, I got

> Invalid call. Nonexistent function 'send_image' in base 'Spout'.

I also get the following errors, which seem like they're probably related:

```
E 0:00:00:0583   godot::ClassDB::bind_methodfi: Method 'Spout::send_texture()' definition has more arguments than the actual method.
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   godot-cpp\src\core\class_db.cpp:160 @ godot::ClassDB::bind_methodfi()
```

```
E 0:00:00:0583   godot::ClassDB::bind_methodfi: Method 'Spout::send_image()' definition has more arguments than the actual method.
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   godot-cpp\src\core\class_db.cpp:160 @ godot::ClassDB::bind_methodfi()
```

**Comment by you-win** [comment]
Thanks for opening the issue, the problem was that I had accidentally registered `send_fbo` to all 3 `send_*` GDScript functions. This should be fixed on the latest `master` code.

**Comment by MorseAmalgam** [comment]
Thank you! I can confirm that fixed the issues.
